name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - run: dotnet run --project "build/Robots.Build/Robots.Build.csproj" test build package publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YAK_TOKEN: ${{ secrets.YAK_TOKEN }}
